

# iCloud
ICLOUD_USERNAME = '{ICLOUD USERNAME}'
ICLOUD_PASSWORD = '{ICLOUD PASSWORD}'

# Fitbit
FITBIT_USERNAME = '{FITBIT USERNAME}'
FITBIT_PASSWORD = '{FITBIT PASSWORD}'
FITBIT_API_KEY = '{FITBIT API KEY}'